### ISSUE TITLE
Update Row Fail

### ISSUE THREAD

**Issue by quanganh206** [odoogap/vuestorefront#5]
### Environment
Odoo: 15.0
VSF Plugin: 15.0

### Installed successfully
<img width="1697" alt="Screen Shot 2022-09-21 at 11 25 54" src="https://user-images.githubusercontent.com/12064619/191414350-1e2261f9-fcaf-4a2d-a869-147649acbcba.png">

### Error
Can not run the updated row function. Always return 404 with endpoint http://odoo:8088/graphql/vsf. Do we need to run with default PORT?

**Comment by quanganh206** [comment]
Capture Error
`
$ node hooks/execute.js routes
ℹ ODOO  - Started fetch (product|categories) to build custom routes...                                               13:13:40
(node:42352) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/Users/xxx/refer/odoo/odoovsf/vuestorefront-demos/demo-1/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/xxx/refer/odoo/odoovsf/vuestorefront-demos/demo-1/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/xxx/refer/odoo/odoovsf/vuestorefront-demos/demo-1/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:42352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:42352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 0.81s.
`

**Comment by quanganh206** [comment]
Solved, reference wrong odoo host.
